apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client # Nome que configuramos no seu lab
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: dados-site
          mountPath: /usr/share/nginx/html # Onde o site guarda os arquivos
      volumes:
      - name: dados-site
        persistentVolumeClaim:
          claimName: site-pvc
