apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-php
  labels:
    app: site-php
spec:
  replicas: 4
  selector:
    matchLabels:
      app: site-php
  template:
    metadata:
      labels:
        app: site-php
    spec:
      containers:
      - name: php-container
        image: saulosneiva/meu-site-php:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-php-service
spec:
  selector:
    app: site-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# ESTA É A PEÇA QUE FALTAVA:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-php-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: meu-site.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: site-php-service
            port:
              number: 80
