apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-php
  labels:
    app: site-php
spec:
  replicas: 4 # Mantendo suas 4 réplicas para alta disponibilidade
  selector:
    matchLabels:
      app: site-php
  template:
    metadata:
      labels:
        app: site-php
    spec:
      containers:
      - name: php-container
        # AJUSTADO: Usando sua imagem própria do Docker Hub
        image: saulosneiva/meu-site-php:latest
        # Força o K8s a baixar a imagem sempre que houver um novo push
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-php-service
spec:
  selector:
    app: site-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
