apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site
  labels:
    app: meu-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-site
  template:
    metadata:
      labels:
        app: meu-site
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meu-site-svc
spec:
  selector:
    app: meu-site
  ports:
  - port: 80
    targetPort: 80
