---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-site
spec:
  replicas: 4
  selector:
    matchLabels:
      app: meu-site
  template:
    metadata:
      labels:
        app: meu-site
    spec:
      containers:
      - name: php-app
        image: php:8.2-apache
        command: ["/bin/sh", "-c"]
        args:
          - |
            docker-php-ext-install mysqli && 
            docker-php-ext-enable mysqli && 
            apache2-foreground
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_PASSWORD
          value: senha123
        volumeMounts:
        - name: dados-site
          mountPath: /var/www/html
      volumes:
      - name: dados-site
        persistentVolumeClaim:
          claimName: site-pvc
